language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35 TRAV_DIST="sdist bdist_wheel"
    - python: 3.4
      env: TOXENV=py34 TRAV_DIST="sdist bdist_wheel"
    - python: 3.3
      env: TOXENV=py33 TRAV_DIST="sdist bdist_wheel"

install: pip install tox

script: tox

deploy:
  - provider: pypi
    user: {{ cookiecutter.travis_ci_username }}
    password:
      secure:
    distributions: $TRAV_DIST
    on:
      tags: true
  - provider: releases
    api_key:
      secure:
    on:
      repo: {{ cookiecutter.github_user }}/{{ cookiecutter.github_project }}
      python: 3.5
      tags: true

notifications:
  slack:
    secure:
  email: false
